name: HTTP

 

on:
  push:
    branches: ["main"] 
jobs:
  cd-prod:

 

    runs-on: ubuntu-latest

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v3

    - name: Deploy Docker 
      env:
        DOCKER_USER: ${{ secrets.DOCKER_USER }}
        DOCEK_TOKEN: ${{ secrets.DOCEK_TOKEN }}
      run: |
        docker login -u $DOCKER_USER -p $DOCEK_TOKEN
        docker build . -t victoremannueluna/http-app:latest
        docker push victoremannueluna/http-app:latest 
